[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

# React SPA: all routes go to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional) Force canonical domain — edit to your real domain if/when ready
[[redirects]]
  from = "https://www.gxpainting.com/*"
  to = "https://gxpainting.com/:splat"
  status = 301
  force = true
