[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "https://www.gxpainting.com/*"
  to = "https://gxpainting.com/:splat"
  status = 301
  force = true
