[build]
  command = "npm run build"
  publish = "dist/client"

[functions]
  directory = "netlify/functions"

# React SPA: all routes go to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Force apex domain (edit to your real domain if needed)
[[redirects]]
  from = "https://www.gxpainting.com/*"
  to = "https://gxpainting.com/:splat"
  status = 301
  force = true
